### PR TITLE
Update dockerfile and edit bot.json

### PR DESCRIPTION
**Pull request by ffahri**
Updated dockerfile to https://hub.docker.com/r/yoannm/archisteamfarm/~/dockerfile/ 
and bot.json add "" for specify.

### CODE REVIEW

**Review by YoannMa — COMMENTED** [review]
I set `SteamLogin` and `SteamPassword` on `null` to allow people to start the container without specifying a configuration. 

When starting with a `null` value, ASF will ask the login & password.

Do you think it's better to have it with a bad value instead of a `null` value ?

**Comment by ffahri** [comment]
oh sorry ,yep my bad. Im pressing enter so wont see the asking part bypassing with empty. So i make to hardcoded.

**Comment by YoannMa** [comment]
No worries. By the way, why did you add `apt-utils` ?

**Comment by ffahri** [comment]
For pressing this warning it does work without it tho.
getting this warning
debconf: delaying package configuration, since apt-utils is not installed
 -- out-link https://serverfault.com/questions/358943/what-does-debconf-delaying-package-configuration-since-apt-utils-is-not-insta/358950

**Comment by YoannMa** [comment]
Oh, thanks for that. If it's ok with you, i'll close this PR and make the change directly to `master` on the appropriate file in a couple of hours.

**Pull request closed without merging**
